import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  overview: [{type: 'autogenerated', dirName: 'overview'}],
  getStarted: [{type: 'autogenerated', dirName: 'get-started'}],
  coreConcepts: [{type: 'autogenerated', dirName: 'core-concepts'}],
  packages: [{type: 'autogenerated', dirName: 'packages'}],
  scenarios: [{type: 'autogenerated', dirName: 'scenarios'}],
  aiCoder: [{type: 'autogenerated', dirName: 'ai-coder'}],
  integrations: [{type: 'autogenerated', dirName: 'integrations'}],
  governance: [{type: 'autogenerated', dirName: 'governance'}],
  specification: [{type: 'autogenerated', dirName: 'specification'}],
  contribute: [{type: 'autogenerated', dirName: 'contribute'}],
  resources: [{type: 'autogenerated', dirName: 'resources'}],
  announcements: [{type: 'autogenerated', dirName: 'announcements'}]
};

export default sidebars;
